/vis/scene/create

# Create a scene handler for a specific graphics system
# (Edit the next lines(s) to choose another graphics system
#/vis/open OGLIX
/vis/open OGLIX 600x600-0+0
#/vis/open OGL


# Draw Scene
#
/vis/viewer/set/style surface
/vis/viewer/set/lightsThetaPhi 90 0 deg
#/vis/viewer/set/viewpointThetaPhi 90 90 deg
#/vis/viewer/zoom 1.5
/vis/viewer/set/upVector 0 0 1
/vis/viewer/addCutawayPlane 0 0 0 m 1 0 0
/vis/viewer/set/viewpointVector -1 0 0
#/vis/viewer/set/viewpointVector 0 0 1 
#/vis/viewer/zoom 1.5


#make some special colors
/tracking/storeTrajectory 0
/vis/scene/add/trajectories
/vis/modeling/trajectories/create/drawByParticleID
/vis/modeling/trajectories/drawByParticleID-0/setRGBA neutron 1 0.45 0.08 1
/vis/scene/endOfEventAction accumulate -1

#make a generic generator
/gps/particle neutron 
#/gps/position -70.0 0.0 0.0 cm
#/gps/position 0.0 100 -40 cm
/gps/position 0.0 1197.31 -646.79 mm
/gps/pos/type Point
/gps/ang/type iso
/gps/ene/type Arb 
/gps/hist/type arb 
/gps/hist/file sources/pube_skim.dat 
/gps/hist/inter Lin
#/gps/ene/mono 8 MeV

#make a raytrace model
#/vis/rayTracer/eyePosition 1 1 1 m
#/vis/rayTracer/trace



#/CDMS/genericShield/setPosition 100.0 0.0 0.685355 cm
#/CDMS/genericShield/setPosition -70.0 0.0 0.0 cm
#/CDMS/genericShield/setSize 10.0 10.0 20.0 cm
#/CDMS/genericShield/setMat Lead 
#/CDMS/detector/activate GPSShielding 
#/CDMS/detector/deactivate Shields
/CDMS/detector/activate Floor 
/CDMS/detector/activate Frame 
/CDMS/detector/activate IceBox 
/CDMS/detector/activate PuBeSourceAndShield 
#/CDMS/PuBe/Barrel True 
/CDMS/detector/activate Shields
/CDMS/Shield/SouthNaI True 
/CDMS/updateGeometry
/CDMS/updateGeometry
/vis/viewer/zoom 1.5
/vis/viewer/pan 0 100 cm
/vis/viewer/zoom 1.5
/vis/scene/add/text 0.00	33.02	0.00 cm 24 0 0 x
/vis/scene/add/text 0.00	42.65	-7.19 cm 24 0 0 x
/vis/scene/add/text 0.00	52.29	-14.37 cm 24 0 0 x
/vis/scene/add/text 0.00	61.92	-21.56 cm 24 0 0 x
/vis/scene/add/text 0.00	71.56	-28.75 cm 24 0 0 x
/vis/scene/add/text 0.00	81.19	-35.93 cm 24 0 0 x
/vis/scene/add/text 0.00	90.83	-43.12 cm 24 0 0 x
/vis/scene/add/text 0.00	100.46	-50.31 cm 24 0 0 x
/vis/scene/add/text 0.00	110.10	-57.49 cm 24 0 0 x
/vis/scene/add/text 0.00	119.73	-64.68 cm 24 0 0 x

/vis/ogl/set/printMode pixmap
/vis/ogl/set/printFilename FluxScan0_Positions     
/vis/ogl/printEPS
#/run/beamOn 3 
